export enum JobTypes {
  SQL_FUNCTION = 'SQL_FUNCTION',
  SQL_PROCEDURE = 'SQL_PROCEDURE',
  TABLEAU_EXTRACT_REFRESH_TASK = 'TABLEAU_EXTRACT_REFRESH_TASK',
  FIVETRAN_CONNECTOR = 'FIVETRAN_CONNECTOR',
  DBT_MODEL = 'DBT_MODEL',
  POWER_BI_REFRESH = 'POWER_BI_REFRESH',
  POWER_BI_DATAFLOW = 'POWER_BI_DATAFLOW',
  ADF_ACTIVITY = 'ADF_ACTIVITY',
  ADF_PIPELINE = 'ADF_PIPELINE',
  JOB = 'JOB',
  ACTIVITY = 'ACTIVITY',
  PIPELINE = 'PIPELINE',
  PACKAGE = 'PACKAGE',
  COMPONENT = 'COMPONENT',
  TASK = 'TASK',
  SNOWFLAKE_PIPE = 'SNOWFLAKE_PIPE',
  AWS_LAMBDA = 'AWS_LAMBDA'
}

export type JobType =
  | 'SQL_FUNCTION'
  | 'SQL_PROCEDURE'
  | 'TABLEAU_EXTRACT_REFRESH_TASK'
  | 'FIVETRAN_CONNECTOR'
  | 'DBT_MODEL'
  | 'POWER_BI_REFRESH'
  | 'POWER_BI_ACTIVITY'
  | 'POWER_BI_DATAFLOW'
  | 'ADF_PIPELINE'
  | 'ADF_ACTIVITY'
  | 'ACTIVITY'
  | 'JOB'
  | 'DATAFLOW'
  | 'PIPELINE'
  | 'PACKAGE'
  | 'COMPONENT'
  | 'REFRESH'
  | 'TASK'
  | 'SNOWFLAKE_PIPE'
  | 'AWS_LAMBDA';

export function isJobType(input: string): input is JobType {
  return Object.keys(JobTypes).includes(input);
}
