process.env.PLATFORM_CORE_API_URL_BASE = 'http://test:3000/v1';
process.env.PUBLISH_ANALZYER_BATCH_SLEEP_IN_MILLISECONDS = '1';
process.env.APPLICATION_POSTGRES_ENCRYPTION_KEY = 'k1.aesgcm256.DL2G9PQeZ9r65J59pph6dy9Sk4fBLEZ3CTQZsandgYE=';
